### ISSUE TITLE
Add support for Static IP assignment for NICs

### ISSUE THREAD

**Issue by janegilring** [crayon/terraform-azurerm-vm#15]
![image](https://user-images.githubusercontent.com/2039662/131573681-f358ebd9-e24f-4ebd-a34e-f3dbf5b52e3f.png)

Support for Static IP assignment for NICs is useful in scenarios such as Domain Controllers being started/stopped due to uptime policies. In addition to enabling Static IP, it should also be possible to specify an IP address.

**Comment by roberthstrand** [comment]
To solve this type of issue, we have the variable `network_interface_ids` where you can define your own network interface instead of defining a subnet for which network interfaces will be automatically generated. This means that one has to either define `network_interface_subnets` or `network_interface_ids`, and one cannot combine the two. Also the point of having this module is for it to take care of as much as possible of the lifecycle to the VM, which also include the NICs.

What I'm going to do is give the `network_interface_subnets` the additional attributes for choosing _Dynamic_ or _Static_ assignment, and make it possible for specifying the IP. This makes the object a little heavy, one needs to define all attributes until the optional setting is out of the experimental phase, but I think it's worth it. The BYO-NIC option will still be there for legacy or (possible) easier importing.

Noticed also that an optional setting for ip_configuration called `primary`. This is something not defined now, and I something I think we can fix programmatically. Haven't heard of anyone having issues with multiple NICs but better safe than sorry. Opened #16 to solve this, added to milestone v1.10.
